### ISSUE TITLE
好像直接copynearby页的urlc转请求就OK了

### ISSUE THREAD

**Issue by Tomazi722** [wongzeon/query_covid19_vaccine_shenzhen#2]
哈哈哈哈你的抓包获取可以直接用参数代替不，

**Comment by wongzeon** [comment]
主要是页面的headers有不同的参数，还有就是那个reservationaddr那个页面post的信息，里面的话参数不同，是个人的信息，直接抓包替换就好啦。

**Comment by Tomazi722** [comment]
对了你的逻辑里面漏了翻页

**Comment by wongzeon** [comment]
不是漏了，故意的，只要看第一页就够了，有号一般不会过一页🤣

**Comment by wongzeon** [comment]
只需要加个for循环就可以翻页了，福田总共就7页，观察了规律，它会自动将有号的放到前面，所以看前面就好啦，有其他需求的话加上也没事，不过不能太快，太快会被拉黑一段时间😂

**Comment by Tomazi722** [comment]
噢！我拿到的好像没有自动放前面，另外尝试post预约信息，没成功，感觉参数没传对，直接{'ecode': '1001', 'msg': 'Http Message Not Readable'}

**Comment by Tomazi722** [comment]
问一段时间是多久？

**Comment by wongzeon** [comment]
你可以看看页面，是不是约满的排前面，未放号的排后面，是的话，应该还是按这个规律排的。提交预约我没弄，因为怕约到不合适的时段。它请求的是带有padID（应该是每个社康的唯一编号）的页面，你可以看看是不是Headers有变化

**Comment by Tomazi722** [comment]
嗯嗯是的需要社康编号，但是传参不难，主要是我直接复制他的header也没成功，另外是不是很多假库存？经常有些库存5的

**Comment by wongzeon** [comment]
> 问一段时间是多久？

大概5～10分钟，访问频率不太高一般不触发，我是访问了三个区，那时候有翻页，一下就被拉黑了😂

**Comment by Tomazi722** [comment]
我两秒请一次2个区好像还好

**Comment by wongzeon** [comment]
> 嗯嗯是的需要社康编号，但是传参不难，主要是我直接复制他的header也没成功，另外是不是很多假库存？经常有些库存5的

库存5应该只是个状态参数，只要可预约就一定是5，它判断可否预约需要nums和status和stock同时满足

**Comment by wongzeon** [comment]
> 我两秒请一次2个区好像还好

嗯，推荐只看一两页就好了，后面的没啥必要，也可以根据社康ID看自己想要的社康情况

**Comment by Tomazi722** [comment]
我还以为是真实的stock, 那要看到真实的stock只能看https://xgsz.szcdc.net/crmobile/reservationStock/timeNumber?

**Comment by Tomazi722** [comment]
> > 我两秒请一次2个区好像还好
> 
> 嗯，推荐只看一两页就好了，后面的没啥必要，也可以根据社康ID看自己想要的社康情况

soga！感谢

**Comment by wongzeon** [comment]
> 我还以为是真实的stock, 那要看到真实的stock只能看https://xgsz.szcdc.net/crmobile/reservationStock/timeNumber?

嗯，真实的库存在预约页面里。

**Comment by wongzeon** [comment]
> > > 我两秒请一次2个区好像还好
> > 
> > 
> > 嗯，推荐只看一两页就好了，后面的没啥必要，也可以根据社康ID看自己想要的社康情况
> 
> soga！感谢

客气了～

**Comment by publiclassperson** [comment]
> > 我两秒请一次2个区好像还好
> 
> 嗯，推荐只看一两页就好了，后面的没啥必要，也可以根据社康ID看自己想要的社康情况

不用翻页来着,一页设置20/30/50等于翻页

**Comment by wongzeon** [comment]
> > > 我两秒请一次2个区好像还好
> > 
> > 
> > 嗯，推荐只看一两页就好了，后面的没啥必要，也可以根据社康ID看自己想要的社康情况
> 
> 不用翻页来着,一页设置20/30/50等于翻页

嗯，是可以设置一页数据，不过其实默认的10个也够了，不消耗服务器太多了。往往是提示有，点击进去的时候已经预约完了，打到就好了，祝健康~
