### ISSUE TITLE
已成功预约并接种,科兴疫苗,谢谢大佬!

### ISSUE THREAD

**Issue by publiclassperson** [wongzeon/query_covid19_vaccine_shenzhen#4]
说几个遇到的问题吧.
1.ids那个参数没有用到
2.企业微信通知点不开,于是自己换成了bark
3.示例图里遇到了5库存,实际上并没有库存,无法预约到,属于错误数据.

**Comment by wongzeon** [comment]
那个stock字段是状态来的，不是真实的库存，在readme写啦。判断可否预约需要nums、status、stock同时满足条件才可以的~ #2 可以看看这个issue~

**Comment by wongzeon** [comment]
> 说几个遇到的问题吧.
> 1.ids那个参数没有用到
> 2.企业微信通知点不开,于是自己换成了bark
> 3.示例图里遇到了5库存,实际上并没有库存,无法预约到,属于错误数据.

ids那个是post `https://imm.szcdc.net/miWeixin/wx/reservation/getReservationAddr` 请求体里面有的，抓包看得到~所以就没有省略了
企业微信那个，得通过创建应用发消息，机器人我没测试。如果是用的markdown类型的话，就会提示要去企业微信查看，如果是应用的话，则会在“企业号应用”之中显示。不过有其他的方法解决也ok，server酱也可以的。

**Comment by Tomazi722** [comment]
其实我发现浏览器也可以直接抓，在跳转到去预约那一页就可以用浏览器打开，然后直接复制header就OK，不会有需要微信浏览器打开的提示

**Comment by wongzeon** [comment]
> 其实我发现浏览器也可以直接抓，在跳转到去预约那一页就可以用浏览器打开，然后直接复制header就OK，不会有需要微信浏览器打开的提示

是的，并且那个页面，已经预约成功了，打过疫苗的也还能进去，并且能再提交，应该算是BUG吧
